/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author serpi
 */


public class DatosDeCuentas extends javax.swing.JPanel {

    private DefaultListModel modeloDeProductos;
    public DatosDeCuentas() {
        modeloDeProductos = new DefaultListModel();
        initComponents();
        iniciarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        jList1.setModel(modeloDeProductos);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       actualizarLista();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void actualizarLista(){
        int id = 1;
         int x = 0;
        try(DataInputStream buffer = new DataInputStream(new FileInputStream("datos.bin"))){
            modeloDeProductos.clear();
             while(!buffer.equals(null)){
               
            modeloDeProductos.addElement("Cuenta " + id );
            modeloDeProductos.addElement(buffer.readUTF());
            x = buffer.readInt();
            for(int y = 1 ; y <= x ; y++){
            modeloDeProductos.addElement("CAFE # : " + y);
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            }
            id++;
           }
            buffer.close();
        }catch(IOException err){
           // JOptionPane.showMessageDialog(rootPane, "Error Al Leer Documento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

public void iniciarLista(){
           int id = 1;
           int x = 0;
           try(DataInputStream buffer = new DataInputStream(new FileInputStream("Cuentas.bin"))){
           // modeloDeProductos.removeElement(modeloDeProductos.lastElement());
            while(!buffer.equals(null)){
               
            modeloDeProductos.addElement("Cuenta " + id );
            modeloDeProductos.addElement(buffer.readUTF());
            x = buffer.readInt();
            for(int y = 1 ; y <= x ; y++){
            modeloDeProductos.addElement("CAFE # : " + y);
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            modeloDeProductos.addElement(buffer.readUTF());
            }
            id++;
           }
            buffer.close();
           
        }catch(IOException err){
           // JOptionPane.showMessageDialog(rootPane, "Error Al Leer Documento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
