/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe;
import java.awt.Font;

/**
 *
 * @author serpi
 */
public class MenuDeCafes extends javax.swing.JPanel {

    /**
     * Creates new form MenuDeCafes
     */
    public MenuDeCafes() {
        initComponents();
        cambiarMetodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bebidas = new javax.swing.JLabel();
        Latte = new javax.swing.JLabel();
        Machiatto = new javax.swing.JLabel();
        Frapuccino = new javax.swing.JLabel();
        vanilla = new javax.swing.JLabel();
        Espresso = new javax.swing.JLabel();
        Mocha = new javax.swing.JLabel();
        Machiatto1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(null);

        bebidas.setFont(new Font("DK Lemon Yellow Sun.otf",Font.PLAIN,14)
        );
        bebidas.setForeground(new java.awt.Color(255, 255, 255));
        bebidas.setText("CAFÉS");
        bebidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(bebidas);
        bebidas.setBounds(100, 20, 100, 40);

        Latte.setForeground(new java.awt.Color(255, 255, 255));
        Latte.setText("*Latte");
        add(Latte);
        Latte.setBounds(20, 110, 200, 30);

        Machiatto.setForeground(new java.awt.Color(255, 255, 255));
        Machiatto.setText("*Caramel Machiatto");
        add(Machiatto);
        Machiatto.setBounds(20, 295, 170, 30);

        Frapuccino.setForeground(new java.awt.Color(255, 255, 255));
        Frapuccino.setText("*Frapuccino ");
        add(Frapuccino);
        Frapuccino.setBounds(20, 70, 200, 30);

        vanilla.setForeground(new java.awt.Color(255, 255, 255));
        vanilla.setText("*Vanilla");
        add(vanilla);
        vanilla.setBounds(20, 152, 130, 30);

        Espresso.setForeground(new java.awt.Color(255, 255, 255));
        Espresso.setText("*Espresso");
        add(Espresso);
        Espresso.setBounds(20, 188, 120, 30);

        Mocha.setForeground(new java.awt.Color(255, 255, 255));
        Mocha.setText("*Mocha");
        add(Mocha);
        Mocha.setBounds(20, 224, 110, 30);

        Machiatto1.setForeground(new java.awt.Color(255, 255, 255));
        Machiatto1.setText("*Machiatto");
        add(Machiatto1);
        Machiatto1.setBounds(20, 260, 130, 30);
        add(jSeparator1);
        jSeparator1.setBounds(20, 213, 270, 10);
        add(jSeparator2);
        jSeparator2.setBounds(20, 100, 270, 10);
        add(jSeparator3);
        jSeparator3.setBounds(20, 141, 270, 10);
        add(jSeparator4);
        jSeparator4.setBounds(20, 249, 270, 10);
        add(jSeparator5);
        jSeparator5.setBounds(20, 285, 270, 10);
        add(jSeparator6);
        jSeparator6.setBounds(20, 321, 270, 10);
        add(jSeparator7);
        jSeparator7.setBounds(20, 177, 270, 10);

        jLabel1.setText("$35");
        add(jLabel1);
        jLabel1.setBounds(210, 300, 21, 16);

        jLabel2.setText("$20");
        add(jLabel2);
        jLabel2.setBounds(210, 70, 21, 16);

        jLabel3.setText("$25");
        add(jLabel3);
        jLabel3.setBounds(210, 120, 21, 16);

        jLabel4.setText("$20");
        add(jLabel4);
        jLabel4.setBounds(210, 180, 21, 16);

        jLabel5.setText("$20");
        add(jLabel5);
        jLabel5.setBounds(210, 150, 21, 16);

        jLabel6.setText("$30");
        add(jLabel6);
        jLabel6.setBounds(210, 220, 21, 16);

        jLabel7.setText("$30");
        add(jLabel7);
        jLabel7.setBounds(210, 260, 21, 16);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);
        jCheckBox2.setBounds(250, 288, 40, 40);

        buttonGroup1.add(jCheckBox8);
        jCheckBox8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        add(jCheckBox8);
        jCheckBox8.setBounds(250, 65, 40, 40);

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3);
        jCheckBox3.setBounds(250, 105, 40, 40);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        add(jCheckBox4);
        jCheckBox4.setBounds(250, 180, 40, 40);

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        add(jCheckBox5);
        jCheckBox5.setBounds(250, 145, 40, 40);

        buttonGroup1.add(jCheckBox6);
        jCheckBox6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        add(jCheckBox6);
        jCheckBox6.setBounds(250, 216, 40, 40);

        buttonGroup1.add(jCheckBox7);
        jCheckBox7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox blanco.png"))); // NOI18N
        jCheckBox7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkbox seleccionado.png"))); // NOI18N
        jCheckBox7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCheckBox7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        add(jCheckBox7);
        jCheckBox7.setBounds(250, 252, 40, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Espresso;
    private javax.swing.JLabel Frapuccino;
    private javax.swing.JLabel Latte;
    private javax.swing.JLabel Machiatto;
    private javax.swing.JLabel Machiatto1;
    private javax.swing.JLabel Mocha;
    private javax.swing.JLabel bebidas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel vanilla;
    // End of variables declaration//GEN-END:variables

private void cambiarMetodo() {
        ClaseYellow cf = new ClaseYellow("Cream Cake.ttf");
        ClaseYellow st  = new ClaseYellow("Sweety Strawberry.ttf");
        
        bebidas.setFont(st.MyFont(1, 30));
        Latte.setFont(cf.MyFont(0, 30));
        Frapuccino.setFont(cf.MyFont(0, 30));
        vanilla.setFont(cf.MyFont(0, 30));
        Espresso.setFont(cf.MyFont(0, 30));
        Mocha.setFont(cf.MyFont(0, 30));
        Machiatto.setFont(cf.MyFont(0, 30));
        Machiatto1.setFont(cf.MyFont(0, 30));
        
    }

}
