package cafe;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author emili
 */
public class TerminarPedido extends javax.swing.JPanel {

    //Para manipular la fecha 
    Date fechaActual = new Date ();
    SimpleDateFormat sdf = new SimpleDateFormat ("dd/MM/yyyy");
    
    /**
     * Creates new form TerminarPedido
     */
    public TerminarPedido() {
        initComponents();
        cambiarMetodo();
        fechas();
        datosIniciales();
    }

    private void fechas(){
        System.out.println(fechaActual);
        System.out.println(sdf.format(fechaActual));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTerminar = new javax.swing.JLabel();
        vasitoCafe = new javax.swing.JLabel();
        labelCafe = new javax.swing.JLabel();
        labelTamanio = new javax.swing.JLabel();
        labelJarabe = new javax.swing.JLabel();
        labelNumShot = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelLeche = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        labelTerminar.setForeground(new java.awt.Color(255, 255, 255));
        labelTerminar.setText("Concluir Pedido");
        add(labelTerminar);
        labelTerminar.setBounds(150, 20, 150, 50);

        vasitoCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cafe_Vaso.png"))); // NOI18N
        add(vasitoCafe);
        vasitoCafe.setBounds(10, 100, 202, 258);

        labelCafe.setForeground(new java.awt.Color(255, 255, 255));
        labelCafe.setText("Cafe: ");
        add(labelCafe);
        labelCafe.setBounds(230, 80, 160, 40);

        labelTamanio.setForeground(new java.awt.Color(255, 255, 255));
        labelTamanio.setText("Tamaño: ");
        add(labelTamanio);
        labelTamanio.setBounds(230, 200, 170, 50);

        labelJarabe.setForeground(new java.awt.Color(255, 255, 255));
        labelJarabe.setText("Jarabe: ");
        add(labelJarabe);
        labelJarabe.setBounds(200, 270, 210, 60);

        labelNumShot.setForeground(new java.awt.Color(255, 255, 255));
        labelNumShot.setText("Num Shots: ");
        add(labelNumShot);
        labelNumShot.setBounds(230, 330, 160, 60);

        btnFinalizarCompra.setText("Comprar");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        add(btnFinalizarCompra);
        btnFinalizarCompra.setBounds(325, 440, 80, 32);

        jButton2.setText("Seguir comprando");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(172, 440, 135, 32);

        labelLeche.setForeground(new java.awt.Color(255, 255, 255));
        labelLeche.setText("Leche:");
        add(labelLeche);
        labelLeche.setBounds(230, 130, 160, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cafeteria.getCuenta().getListaCafe().add(Cafeteria.getCuenta().getCafe());
        Cafeteria.getCuenta().setCafeAux(new Cafe()); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        Cafeteria.getCuenta().getListaCafe().add(Cafeteria.getCuenta().getCafe());
        Cafeteria.getCuentasDelRestaurante().add(Cafeteria.getCuenta());
        for(int x=0; x<Cafeteria.getCuenta().getListaCafe().size();x++){
            
            System.out.println(Cafeteria.getCuenta().getListaCafe().get(x).getNombreCafe()+ "   " +
            Cafeteria.getCuenta().getListaCafe().get(x).getNumShots()+ "   " +
            Cafeteria.getCuenta().getListaCafe().get(x).getVaso().toString()+ "   " +
            Cafeteria.getCuenta().getListaCafe().get(x).getNombreJarabe()+ "   " +
            Cafeteria.getCuenta().getListaCafe().get(x).getLeche().toString());
            
//            Cafeteria.getCuenta().getListaCafe().get(x).getNombreCafe();
//            Cafeteria.getCuenta().getListaCafe().get(x).getNumShots();
//            Cafeteria.getCuenta().getListaCafe().get(x).getVaso().toString();
//            Cafeteria.getCuenta().getListaCafe().get(x).getNombreJarabe();
//            Cafeteria.getCuenta().getListaCafe().get(x).getLeche().toString();
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed
                               

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelCafe;
    private javax.swing.JLabel labelJarabe;
    private javax.swing.JLabel labelLeche;
    private javax.swing.JLabel labelNumShot;
    private javax.swing.JLabel labelTamanio;
    private javax.swing.JLabel labelTerminar;
    private javax.swing.JLabel vasitoCafe;
    // End of variables declaration//GEN-END:variables

private void cambiarMetodo() {
        ClaseYellow cf = new ClaseYellow("Cream Cake.ttf");
        ClaseYellow st  = new ClaseYellow("Sweety Strawberry.ttf");
        ClaseYellow yt  = new ClaseYellow("DK Lemon Yellow Sun.otf");
        
        labelTerminar.setFont(st.MyFont(1, 20));
        labelCafe.setFont(st.MyFont(0, 20));
        labelJarabe.setFont(st.MyFont(0, 20));
        labelNumShot.setFont(st.MyFont(0, 20));
        labelTamanio.setFont(st.MyFont(0, 20));
        labelLeche.setFont(st.MyFont(0, 20));
        
    }

    private void datosIniciales() {

        if(Cafeteria.getCuenta().getCafe() != null){
            if(Cafeteria.getCuenta().getCafe().getNombreCafe()!=null){
                labelCafe.setText("Cafe: " + Cafeteria.getCuenta().getCafe().getNombreCafe());
                labelNumShot.setText("Num Shots: " + Cafeteria.getCuenta().getCafe().getNumShots());
        }
                 else{labelCafe.setText("Cafe:");}
            if(Cafeteria.getCuenta().getCafe().getVaso() != null){
                labelTamanio.setText("Tamaño: " + Cafeteria.getCuenta().getCafe().getVaso().toString() );
            }
            if(Cafeteria.getCuenta().getCafe().getNombreJarabe()!= null){
                labelJarabe.setText("Jarabe: "+ Cafeteria.getCuenta().getCafe().getNombreJarabe());
            }else{labelJarabe.setText("Jarabe: Ninguno");}
            
           if(Cafeteria.getCuenta().getCafe().getLeche()!=null){
                labelLeche.setText("Leche: " + Cafeteria.getCuenta().getCafe().getLeche().toString());
            }
    }
    }
}